stages:
  - test
  - build jar
  - build and push docker image
  - deploy
build:
  image: maven:3.6.2-jdk-8-slim
  stage: build jar
  script:
    - mvn clean install -Dspring.profiles.active=dev && mvn package -B -e -Dspring.profiles.active=dev
  artifacts:
    paths:
      - target/*.jar
  only:
    - master
docker build:
  services:
    - docker:19.03.13-dind
  image: docker:19.03.13-dind
  stage: build and push docker image
  script:
    - docker build --build-arg SPRING_ACTIVE_PROFILE=dev -t $DOCKER_KAFKA_REPO:latest .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
    - docker push $DOCKER_KAFKA_REPO:latest
  only:
    - master
deploy:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - pwd
    - ssh root@$SERVER "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io; docker stop $KAFKA_APP_NAME; docker system prune -a -f; docker pull $DOCKER_KAFKA_REPO:latest; docker-compose -f docker-compose-kafka.yml up -d; docker logout"
  only:
    - master
